services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    restart: always
    command: "azurite --blobHost 0.0.0.0 --blobPort 10000"
    ports:
      - 10000:10000

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgresql:/docker-entrypoint-initdb.d
    networks:
      - db_network

  fastapi:
    build:
      context: ./api/
      dockerfile: Dockerfile
    depends_on:
      - postgres
    restart: on-failure
    ports:
      - 8000:8000
    networks:
      - db_network

networks:
 db_network: